// src/components/interactive/SFTvsRLComparison.tsx
import { useState, useRef, useEffect } from 'react';
import { COLORS, FONTS } from './shared/colors';

const W = 580;
const H = 480;

// Simulated token generation sequences
// SFT side: follows demo perfectly until it deviates, then cascading errors
// RL side: explores, gets reward, improves over rounds

interface TokenStep {
  token: string;
  prob: number; // model confidence
  status: 'correct' | 'wrong' | 'explored' | 'improved';
}

const PROMPT = '请解释量子纠缠';

const SFT_DEMO: TokenStep[] = [
  { token: '量子', prob: 0.92, status: 'correct' },
  { token: '纠缠', prob: 0.88, status: 'correct' },
  { token: '是', prob: 0.85, status: 'correct' },
  { token: '一个', prob: 0.45, status: 'wrong' },   // deviation begins
  { token: '复杂', prob: 0.22, status: 'wrong' },   // compounding error
  { token: '...', prob: 0.10, status: 'wrong' },     // collapse
];

const RL_ROUNDS: { round: string; tokens: TokenStep[] }[] = [
  {
    round: 'Round 1',
    tokens: [
      { token: '量子', prob: 0.60, status: 'explored' },
      { token: '力学', prob: 0.35, status: 'explored' },
      { token: '中', prob: 0.30, status: 'explored' },
    ],
  },
  {
    round: 'Round 2',
    tokens: [
      { token: '量子', prob: 0.78, status: 'improved' },
      { token: '纠缠', prob: 0.65, status: 'improved' },
      { token: '是指', prob: 0.55, status: 'improved' },
    ],
  },
  {
    round: 'Round 3',
    tokens: [
      { token: '量子', prob: 0.91, status: 'improved' },
      { token: '纠缠', prob: 0.87, status: 'improved' },
      { token: '描述', prob: 0.80, status: 'improved' },
    ],
  },
];

const statusColor = (s: TokenStep['status']) => {
  switch (s) {
    case 'correct': return COLORS.green;
    case 'wrong': return COLORS.red;
    case 'explored': return COLORS.orange;
    case 'improved': return COLORS.green;
  }
};

export default function SFTvsRLComparison({ locale = 'zh' }: { locale?: 'zh' | 'en' }) {
  const t = locale === 'zh' ? {
    title: 'SFT vs RL：两种学习方式的对比',
    sftTitle: 'SFT (Behavioral Cloning)',
    rlTitle: 'RL (Policy Optimization)',
    prompt: '提示词',
    sftProblem: '偏离示范后错误累积 (Distribution Shift)',
    rlAdvantage: '从自己的生成中学习，持续改进',
    collapse: '→ 模型崩溃：进入训练中未见过的状态',
    selfImprove: '→ 自我进化：每轮数据由当前策略生成',
    clickToAnimate: '点击播放动画',
    sftPhase: '训练时只看示范',
    rlPhase: '从 reward 中学习',
  } : {
    title: 'SFT vs RL: Two Learning Paradigms',
    sftTitle: 'SFT (Behavioral Cloning)',
    rlTitle: 'RL (Policy Optimization)',
    prompt: 'Prompt',
    sftProblem: 'Errors compound after deviation (Distribution Shift)',
    rlAdvantage: 'Learns from own generations, improves continuously',
    collapse: '→ Model collapse: enters unseen states',
    selfImprove: '→ Self-improvement: data generated by current policy',
    clickToAnimate: 'Click to animate',
    sftPhase: 'Trained on demos only',
    rlPhase: 'Learns from reward',
  };

  const [sftStep, setSftStep] = useState(0);
  const [rlRound, setRlRound] = useState(0);
  const [animating, setAnimating] = useState(false);

  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, []);

  const animate = () => {
    if (animating) return;
    if (timerRef.current) clearInterval(timerRef.current);
    setAnimating(true);
    setSftStep(0);
    setRlRound(0);
    let step = 0;
    timerRef.current = setInterval(() => {
      step++;
      if (step <= SFT_DEMO.length) setSftStep(step);
      if (step === 2) setRlRound(1);
      if (step === 4) setRlRound(2);
      if (step === 6) setRlRound(3);
      if (step > 6) {
        if (timerRef.current) clearInterval(timerRef.current);
        timerRef.current = null;
        setAnimating(false);
      }
    }, 500);
  };

  const leftX = 20, rightX = W / 2 + 10, panelW = W / 2 - 30;

  return (
    <div>
      <svg viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ fontFamily: FONTS.sans }}>
        {/* Title */}
        <text x={W / 2} y={22} textAnchor="middle" fontSize={15} fontWeight={700} fill={COLORS.dark}>
          {t.title}
        </text>
        {/* Divider */}
        <line x1={W / 2} y1={36} x2={W / 2} y2={H - 50}
          stroke={COLORS.light} strokeWidth={1} strokeDasharray="4,4" />

        {/* === SFT Panel === */}
        <text x={leftX + panelW / 2} y={50} textAnchor="middle" fontSize={13}
          fontWeight={700} fill={COLORS.primary}>{t.sftTitle}</text>
        <text x={leftX + panelW / 2} y={68} textAnchor="middle" fontSize={10}
          fill={COLORS.mid}>{t.sftPhase}</text>
        <rect x={leftX + 10} y={80} width={panelW - 20} height={24} rx={4}
          fill={COLORS.highlight} />
        <text x={leftX + 20} y={96} fontSize={10} fill={COLORS.dark}>
          {t.prompt}: {PROMPT}
        </text>
        {/* SFT tokens with confidence bars */}
        {SFT_DEMO.slice(0, sftStep).map((tk, i) => {
          const y = 120 + i * 36;
          const barW = tk.prob * (panelW - 100);
          return (
            <g key={`sft-${i}`}>
              <text x={leftX + 15} y={y + 14} fontSize={10} fill={COLORS.dark}>
                {i + 1}. "{tk.token}"
              </text>
              <rect x={leftX + 100} y={y + 2} width={barW} height={16} rx={3}
                fill={statusColor(tk.status)} opacity={0.7} />
              <text x={leftX + 105 + barW} y={y + 14} fontSize={9} fill={COLORS.mid}>
                {(tk.prob * 100).toFixed(0)}%
              </text>
            </g>
          );
        })}
        {sftStep >= SFT_DEMO.length && (
          <g>
            <rect x={leftX + 10} y={340} width={panelW - 20} height={28} rx={6}
              fill={COLORS.waste} />
            <text x={leftX + panelW / 2} y={358} textAnchor="middle" fontSize={10}
              fontWeight={600} fill={COLORS.red}>{t.collapse}</text>
            <text x={leftX + panelW / 2} y={385} textAnchor="middle" fontSize={10}
              fontWeight={600} fill={COLORS.red}>{t.sftProblem}</text>
          </g>
        )}

        {/* === RL Panel === */}
        <text x={rightX + panelW / 2} y={50} textAnchor="middle" fontSize={13}
          fontWeight={700} fill={COLORS.green}>{t.rlTitle}</text>
        <text x={rightX + panelW / 2} y={68} textAnchor="middle" fontSize={10}
          fill={COLORS.mid}>{t.rlPhase}</text>
        <rect x={rightX + 10} y={80} width={panelW - 20} height={24} rx={4}
          fill={COLORS.highlight} />
        <text x={rightX + 20} y={96} fontSize={10} fill={COLORS.dark}>
          {t.prompt}: {PROMPT}
        </text>
        {/* RL rounds with improving confidence */}
        {RL_ROUNDS.slice(0, rlRound).map((round, ri) => {
          const baseY = 115 + ri * 80;
          return (
            <g key={`rl-${ri}`}>
              <text x={rightX + 15} y={baseY + 10} fontSize={10} fontWeight={600}
                fill={ri === rlRound - 1 ? COLORS.green : COLORS.mid}>
                {round.round} → R={( 0.3 + ri * 0.3).toFixed(1)}
              </text>
              {round.tokens.map((tk, ti) => {
                const y = baseY + 16 + ti * 20;
                const barW = tk.prob * (panelW - 130);
                return (
                  <g key={`rl-${ri}-${ti}`}>
                    <text x={rightX + 20} y={y + 12} fontSize={9} fill={COLORS.dark}>
                      "{tk.token}"
                    </text>
                    <rect x={rightX + 80} y={y} width={barW} height={14} rx={3}
                      fill={statusColor(tk.status)} opacity={0.7} />
                    <text x={rightX + 85 + barW} y={y + 11} fontSize={9} fill={COLORS.mid}>
                      {(tk.prob * 100).toFixed(0)}%
                    </text>
                  </g>
                );
              })}
            </g>
          );
        })}
        {rlRound >= 3 && (
          <g>
            <rect x={rightX + 10} y={340} width={panelW - 20} height={28} rx={6}
              fill={COLORS.valid} />
            <text x={rightX + panelW / 2} y={358} textAnchor="middle" fontSize={10}
              fontWeight={600} fill={COLORS.green}>{t.selfImprove}</text>
            <text x={rightX + panelW / 2} y={385} textAnchor="middle" fontSize={10}
              fontWeight={600} fill={COLORS.green}>{t.rlAdvantage}</text>
          </g>
        )}

        {/* Animate button */}
        <g onClick={animate} style={{ cursor: 'pointer' }}>
          <rect x={W / 2 - 60} y={H - 40} width={120} height={28} rx={14}
            fill={animating ? COLORS.mid : COLORS.primary} />
          <text x={W / 2} y={H - 22} textAnchor="middle" fontSize={11}
            fontWeight={600} fill="#fff">
            {animating ? '...' : t.clickToAnimate}
          </text>
        </g>
      </svg>
    </div>
  );
}
